id: alarm_arm_away
alias: "Alarm: Armed away"
description: ""
triggers:
  - alias: Someone leaves home
    trigger: state
    entity_id:
      - person.chip
      - person.nikki
    to:
      - not_home
    for:
      hours: 0
      minutes: 0
      seconds: 1
    from:
      - home
conditions:
  - condition: and
    conditions:
      - condition: state
        entity_id: person.chip
        state:
          - not_home
      - condition: state
        entity_id: person.nikki
        state:
          - not_home
actions:
  - action: alarm_control_panel.alarm_arm_away
    metadata: {}
    target:
      entity_id: alarm_control_panel.home
    data:
      code: '8355'
  - action: script.send_alarm_state_notification
    metadata: {}
    data:
      alarm_status: Armed Away
mode: single
