id: alarm_arm_away
alias: "Alarm: Armed away"
description: ""
triggers:
  - alias: Everyone leaves home
    trigger: state
    entity_id:
      - binary_sensor.occupancy_alarm_perimeter
    for:
      hours: 0
      minutes: 0
      seconds: 0
    from:
      - "on"
    to:
      - "off"
conditions: []
actions:
  - action: alarm_control_panel.alarm_arm_away
    metadata: {}
    target:
      entity_id: 
        - alarm_control_panel.home_alarm
        - alarm_control_panel.home
    data:
      code: '2440'
  - action: script.send_alarm_state_notification
    metadata: {}
    data:
      alarm_status: Armed Away
mode: single
