id: battery_notes_batery_not_replaced
alias: Battery Not Replaced
description: Battery not replaced
mode: queued
max: 30
triggers:
  - trigger: event
    event_type: battery_notes_battery_not_replaced
conditions: []
actions:
  - action: persistent_notification.create
    data:
      title: |
        {{ trigger.event.data.device_name }} Battery Not Replaced
      message: >
        The device has not been replaced for {{ 
        trigger.event.data.battery_last_replaced_days }} days {{ '\n' 
        -}} Its last replaced date was {{ trigger.event.data.battery_last_replaced 
        | as_timestamp | timestamp_custom('%Y-%m-%d', true)}} {{ '\n' -}} You need 
        {{ trigger.event.data.battery_quantity }}× {{ trigger.event.data.battery_type }}